### ISSUE TITLE
Question: Setup Apache proxy 

### ISSUE THREAD

**Issue by gewooneendeveloper** [voryx/WebSocketMiddleware#1]
Hi,

For almost 2 workdays im trying to setup a working Apache proxy Virtualhost. Without any success. 

Do you have any information or could you give any direction where to find a working example run the ReactPHP http server with the Websocket middleware . 
Here is a example of my struggle : https://github.com/andreaswarnaar/reactphp/blob/api/docker/app/000-default.conf 

Regards,
Andreas Warnaar

**Comment by mbonneau** [comment]
@andreaswarnaar I use nginx as a proxy so I don't have much experience.

I would think this SE answer may help though: https://stackoverflow.com/a/27534443/3500248

**Comment by gewooneendeveloper** [comment]
Thanks, i found this one before but never tried this answer: https://stackoverflow.com/a/35141086/9560612 
This one works well. But without the load balanced setup.
