### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ondrejmirtes** [voryx/WebSocketMiddleware#8]
Hi, although the composer.json states the library is distributed under MIT, there's no LICENSE file in root. [Could you add it?](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) Thank you.

**Comment by mbonneau** [comment]
@ondrejmirtes - Thanks for the heads up. This has been added.

**Comment by ondrejmirtes** [comment]
Thank you :)
